package com.payroute.transaction;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a single payment intent submitted by the caller.
 *
 * Design note on idempotency:
 *   The idempotencyKey is marked UNIQUE in the DB. Before processing, the
 *   orchestrator checks if a Transaction with this key already exists. If so,
 *   it returns the existing result immediately — no second charge, no second
 *   provider call. This mirrors how Stripe handles idempotency keys.
 *
 *   The key should be generated by the caller (or the frontend) per-request,
 *   typically a UUID. Using the client side (not server side) for generation
 *   ensures that retried HTTP calls — e.g., after a network timeout — carry
 *   the same key and are safely deduplicated.
 */
@Entity
@Table(name = "transactions")
@Getter
@Setter
@NoArgsConstructor
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * Caller-supplied deduplication token. UNIQUE constraint ensures the DB
     * itself is the final guard against double-processing, even under race
     * conditions (concurrent requests with the same key will fail on insert).
     */
    @Column(nullable = false, unique = true)
    private String idempotencyKey;

    /** Payment amount in the smallest currency unit (e.g. paise, cents). */
    @Column(nullable = false, precision = 19, scale = 2)
    private BigDecimal amount;

    /**
     * Source identifier — could be a customer ID, card fingerprint, or
     * any opaque string the caller wants to pass. Used by anomaly detection
     * to spot burst activity from the same source.
     */
    @Column(nullable = false)
    private String source;

    /** Final outcome after all routing attempts. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionStatus status;

    /** Which provider ultimately succeeded (null if all failed). */
    private String finalProvider;

    @Column(nullable = false)
    private Instant createdAt;

    private Instant completedAt;

    /**
     * All routing attempts for this transaction, ordered by attempt number.
     * cascade = ALL so attempts are persisted together with the transaction.
     * orphanRemoval = true so deleting the transaction cleans up its attempts.
     */
    @OneToMany(mappedBy = "transaction", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("attemptNumber ASC")
    private List<TransactionAttempt> attempts = new ArrayList<>();

    @PrePersist
    void onCreate() {
        createdAt = Instant.now();
    }
}
